/*refeição(restaurante, tipo_de_alimentação(1,2,3), localização, classificacao, preço_medio_p_pessoa, take_away, entrega, empresa_entrega, custo_entrega)*/

refeição('As Manas',[Portuguesa],'','Sim',
refeição('Bibó Porto',[Portuguesa, Churrasco],'','',
refeição('BiclaBurgers',[Hambúrgueres],'4.8','',
refeição('Big Bobs',[Pizza, FastFood,Italiana],'4.5','',
refeição('Bira dos Namorados',[Hambúrgueres],'4.7','',
refeição('BLB',[Sanduíches],'','',
refeição('Bracara Augusta',[Portuguesa],'','',
refeição('Braga999',[Japonesa],'','Sim',
refeição('BurgerKing',[FastFood,Hambúrgueres,Americana],'4.5','Sim',
refeição('Café do Luís',[Hambúrgueres, Sanduíches],'4.8','',
refeição('Café Vianna',[Portuguesa],'4.5','',
refeição('Caffé Italy',[Pizza, Italiana, Massa],'4.2','',
refeição('Casa da Coxinha',[Latino-Americana],'','',
refeição('Casa Salgado', [Portuguesa], '', '',
refeição('Celeste', [Pizza], '', 'Sim',
refeição('Churrasqueira da Central', [Churrasco], '', 'Sim',
refeição('Churrasqueira Luanda', [Churrasco], '', 'Sim',
refeição('Churrasqueira Oliveira', [Churrasco], '', 'Sim',
refeição('Dgema', [Hambúrgueres], '4.6', 'Sim',
refeição('Docamar', [Marisco], '4.6', 'Sim',
refeição('Eat Fit',[Saudável, Vegetariana, Saladas],'4.8','',
refeição('Foz',[Churrasco],'','',
refeição('Frigideiras da Sé',[Portuguesa],'','',
refeição('Grelhados Maravilha',[Churrasco],'','Sim',
refeição('Gulbenkian Francesinhas',[Portuguesa],'','Sim',
refeição('Habanero',[Mexicana],'4.2','',
refeição('Hanami Sushi',[Sushi, Japonesa],'4.6','',
refeição('Il Fiume',[Italiana, Pizza, Massa],'4.6','',
refeição('Il Fiume',[Italiana],'4.6','',
refeição('Indian Tandoori',[Indiana],'','',
refeição('La Porta',[Italiana],'4.6','',
refeição('Leitaria da Quinta do Paço',[Sobremesas],'4.9','',
refeição('McDonalds',[Hambúrgueres, Americana],'4.6','Sim',
refeição('McDonalds',[Hambúrgueres, ],'4.6','Sim',
